name: 'Composite Cache Action'
description: 'Cache action embedded inside composite action'
runs:
  using: "composite"
  steps:
  - name: Get current date
    shell: bash
    id: date
    run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
  - uses: actions/checkout@v2
  - name: NPM install
    shell: bash
    run: |
      pwd
      npm install
  - uses: actions/cache/restore@700-actionscache-granular-cache-control
    id: cache-restore
    with:
      path: ${{ github.workspace }}/node_modules
      key: cache-key-4
      restore-keys: cache-key-
  - uses: actions/cache/save@700-actionscache-granular-cache-control
    id: cache-save
    with:
      path: ${{ github.workspace }}/node_modules
      key: cache-key-4
